These are the contents of folder "personal" in my .emacs.d folder.

I use emacs-prelude (https://github.com/bbatsov/prelude) to manage configuration.

This loads all emacs-lisp files in folder "preload" first, and then runs init.el.

My init.el first adds all packages from folder "packages" to the load path to make them available.  Then it runs my init file, which is user/iani2.org.

iani2.org contains all the configuration code, as org-babel blocks containing emacs-lisp.

The present repository also contains chuck-mode, for the computer music language ChucK and sclang for SuperCollider.

IZ Dec 23, 2013 (10:52 PM)

* List of packages used

This is an (incomplete) list of the packages used in this configuration.
Mostly use command package-install, or list-packages to install these.
Some of these have been downloaded manually and put in packages folder.

Some of the packages configurations (for example: wanderlust) have not yet been moved to the present file.

** Generic packages for overall Emacs configuration

*** Persistence

(See: http://www.emacswiki.org/emacs/CategoryPersistence)

- desktop :: Automatically save and restore buffer configurations between sessions.
             Note: Works with bookmark+, but interactive interface and settings are unclear as to what gets overwritten when.  So I use my own alternative "simple-desktop" package:
- simple-desktops :: Simple scheme for saving and reloading of file lists, independent of desktop or bookmark+.

*** Windows and buffers

- windmove :: move cursor between windows (using function-shift-cursor keys)
- switch-window :: When more than 2 windows, then select window by number, showing window number in large font overlay.
- buffer-move :: Switch buffer positions in windows (using function-control-cursor keys)

*** Navigating, finding things

- ido-mode :: Basic enhancement of autocomplete for minibuffer.
              But also autocompletion when coding.
- icicles :: More powerful enhancement of autocomplete in all sorts of situations.
             See: http://www.emacswiki.org/emacs/EmacsNewbieWithIcicles
- helm :: Fast navigation for files, folders and commands.  Simpler to use than icicles. (Provided with prelude).  Convenient marking and interactive, incremental grep on files and folders.
- projectile :: Folders become projects, for focussed search and access of files/contents.  Combines with grizzl autocomplete method, which is better suited for display of full paths in match list.  Also grep
                and ack.
- helm-projectile :: Integrate projectile into helm.  Run with C-c p h.
- bookmark+ :: Bookmark enhancement.
- smex :: Enhancement of autocomplete for commands in minibuffer.
- lacarte :: execute menu commands from the keyboard
- AceJump :: Jump to any one of displayed characters/words/lines starting with a character typed (triggered by key-chord combinations).
- dired+ :: Enhancement of dired.
**** for later: ack, ag
- ack-and-a-half :: Perl based search in files.  Used by projectile.  See:
                    http://www.emacswiki.org/emacs/Ack
- ag :: Silver replacement for ack.  See:
        https://github.com/Wilfred/ag.el

*** Snippets and macros

- yasnippets :: Expand keywords into code snippets.
- auto-complete :: Provide auto-completion with popup window

*** Generic authoring/editing packages

- paredit :: Paredit mode.
- rainbow-delimiters-mode :: Multi-color parentheses, brackets, braces.
- hl-sexp-mode (alternative: highlight-sexps-mode) :: highight regions enclosed in parentheses, brackets, braces
- multiple-cursors :: Magnar Sveen's multiple cursor package.
- key-chord :: Trigger a command or keyboard macro by typing two characters in quick succession or together.
- whitespace mode :: mark unnecessary white space and long lines (disabled in org-mode).
- auto-complete :: Provide auto-completion with popup window

*** Display, colors

- solarized-dark :: Additional emacs color theme.

** Packages for specific authoring modes (emacs-lisp, SuperCollider etc.)

*** Emacs-lisp

- ElDoc :: Show arguments required by current function in minibuffer.

*** Org-mode

- org :: Org-mode.
- epresent :: Present slides directly from org-mode.
- calfw :: Present org-mode agenda in calendar-style day, week and month views.
- collector :: Collect property data into org-mode table.
- org-bibedit :: Bibtex integration for orgmode.
- ox-latex :: Latex support
- org-crypt :: Encrypt org-mode entries tagged with =crypt=
- ox-reveal :: Export org-mode files as reveal.js slide presentations.
- org-drill, flashcard, flashcard-sm5 :: Flashcard memorization drill software for org-mode.

*** SuperCollider

- sclang :: SuperCollider.
- sclang-ac-mode :: auto-complete mode for SuperCollider.
- sclang-snippets :: yasnippets for SuperCollider.

Not used, because it seems to interfere with sclang-ac-mode:

- sclang-extensions :: Context sensitive moving and evaluation in SuperCollide

*** ChucK

- chuck :: chuck-mode.

** Other extensions: Email, shells etc.
*** Wanderlust: Email client for emacs

- wanderlust :: Email-client for emacs.
- bbdb-hooks :: Needed for wanderlust.
- bbdb-wl :: Needed for wanderlust.
